id = "yara"
name = "Yara"
version = "0.0.1"
schema_version = 1
authors = ["egibs <evan@egibs.xyz>"]
description = "Yara syntax highlighting for Zed."
repository = "https://github.com/egibs/yara-zed"

[grammars.yara]
repository = "https://github.com/egibs/tree-sitter-yara.git"
commit = "a8058d3fcffa5d61aa66185c976e9f6efbea2a8d"
