name = "Yara"
grammar = "yara"
path_suffixes = ["yar", "yara"]
line_comments = ["//"]
brackets = [
  { start = "{", end = "}", close = true, newline = true },
  { start = "[", end = "]", close = true, newline = true },
  { start = "\"", end = "\"", close = true, newline = false, not_in = [
    "string",
  ] },
]
